language: cpp
compiler: gcc

os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

before_install:
  - sudo add-apt-repository -y ppa:nschloe/boost-nightly
  - sudo apt-get update -qq

install:
  - sudo apt-get install libboost-all-dev

script:
  - cmake --version
  - cmake CMakeLists.txt
  - cmake --build .
  - cmake --build . --target test
  - cmake --build . --target package

deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T helloworld-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -umshestukhin:$BINTRAY_API_KEY "https://api.bintray.com/content/1231321313/02.homework/02.homework/$TRAVIS_BUILD_NUMBER/ip_filter-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
